# Generated by Django 3.1.2 on 2020-10-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStoreModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('occurred_on', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('json', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'event_store',
            },
        ),
    ]
