# Generated by Django 3.1.2 on 2020-12-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accountmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='name',
            new_name='first_name',
        ),
    ]
